name: Tag-Build-Publish-Deploy

on:
  pull_request:
    types: [closed]
    
  
jobs:
  tag:
    runs-on: ubuntu-latest

    if: github.event.pull_request.merged
    
    steps:
      - name: Semver Tag
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-publish:
    needs: tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: kadeksuryam/stand-with-dorayaki-be:${{ needs.tag.outputs.tag }}
      
